apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: test-multiple-import
spec:
  hard:
    pods: "40"
    requests.cpu: "16"
    requests.memory: "32Gi"
    limits.cpu: "32"
    limits.memory: "64Gi"
